# .github/workflows/manual-job.yaml
name: Manual Command Runner

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    name: Run Linux Commands
    runs-on: ubuntu-latest

    steps:
      - name: Run specified commands
        run: |
          echo "Running provided commands:"
          ls -lart
          pwd
          mkdir test
