name: Create AWS EBS Volume

on:
  workflow_dispatch:  # This allows manual triggering
  push:               # Runs on push to main or any branch
    branches:
      - main

jobs:
  create-ebs-volume:
    runs-on: ubuntu-latest

    steps:
   
    # Configure AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
       

    # Create EBS Volume
    - name: Create EBS Volume
      run: |
        aws ec2 create-volume \
          --availability-zone ap-south-1a \
          --size 1 \
          --volume-type gp2

